package builder

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2026-01-21 17:40:56.5217758 +0100 CET m=+0.003738101

import (
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__option "github.com/IBM/fp-go/v2/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
)

// PartialPersonLenses provides lenses for accessing fields of PartialPerson
type PartialPersonLenses struct {
	// mandatory fields
	Name __lens.Lens[PartialPerson, string]
	Age __lens.Lens[PartialPerson, int]
	// optional fields
	NameO __lens_option.LensO[PartialPerson, string]
	AgeO __lens_option.LensO[PartialPerson, int]
}

// PartialPersonRefLenses provides lenses for accessing fields of PartialPerson via a reference to PartialPerson
type PartialPersonRefLenses struct {
	// mandatory fields
	Name __lens.Lens[*PartialPerson, string]
	Age __lens.Lens[*PartialPerson, int]
	// optional fields
	NameO __lens_option.LensO[*PartialPerson, string]
	AgeO __lens_option.LensO[*PartialPerson, int]
	// prisms
	NameP __prism.Prism[*PartialPerson, string]
	AgeP __prism.Prism[*PartialPerson, int]
}

// PartialPersonPrisms provides prisms for accessing fields of PartialPerson
type PartialPersonPrisms struct {
	Name __prism.Prism[PartialPerson, string]
	Age __prism.Prism[PartialPerson, int]
}

// MakePartialPersonLenses creates a new PartialPersonLenses with lenses for all fields
func MakePartialPersonLenses() PartialPersonLenses {
	// mandatory lenses
	lensName := __lens.MakeLensWithName(
		func(s PartialPerson) string { return s.Name },
		func(s PartialPerson, v string) PartialPerson { s.Name = v; return s },
		"PartialPerson.Name",
	)
	lensAge := __lens.MakeLensWithName(
		func(s PartialPerson) int { return s.Age },
		func(s PartialPerson, v int) PartialPerson { s.Age = v; return s },
		"PartialPerson.Age",
	)
	// optional lenses
	lensNameO := __lens_option.FromIso[PartialPerson](__iso_option.FromZero[string]())(lensName)
	lensAgeO := __lens_option.FromIso[PartialPerson](__iso_option.FromZero[int]())(lensAge)
	return PartialPersonLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
	}
}

// MakePartialPersonRefLenses creates a new PartialPersonRefLenses with lenses for all fields
func MakePartialPersonRefLenses() PartialPersonRefLenses {
	// mandatory lenses
	lensName := __lens.MakeLensStrictWithName(
		func(s *PartialPerson) string { return s.Name },
		func(s *PartialPerson, v string) *PartialPerson { s.Name = v; return s },
		"(*PartialPerson).Name",
	)
	lensAge := __lens.MakeLensStrictWithName(
		func(s *PartialPerson) int { return s.Age },
		func(s *PartialPerson, v int) *PartialPerson { s.Age = v; return s },
		"(*PartialPerson).Age",
	)
	// optional lenses
	lensNameO := __lens_option.FromIso[*PartialPerson](__iso_option.FromZero[string]())(lensName)
	lensAgeO := __lens_option.FromIso[*PartialPerson](__iso_option.FromZero[int]())(lensAge)
	return PartialPersonRefLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
	}
}

// MakePartialPersonPrisms creates a new PartialPersonPrisms with prisms for all fields
func MakePartialPersonPrisms() PartialPersonPrisms {
	_fromNonZeroName := __option.FromNonZero[string]()
	_prismName := __prism.MakePrismWithName(
		func(s PartialPerson) __option.Option[string] { return _fromNonZeroName(s.Name) },
		func(v string) PartialPerson {
			return PartialPerson{ Name: v }
		},
		"PartialPerson.Name",
	)
	_fromNonZeroAge := __option.FromNonZero[int]()
	_prismAge := __prism.MakePrismWithName(
		func(s PartialPerson) __option.Option[int] { return _fromNonZeroAge(s.Age) },
		func(v int) PartialPerson {
			return PartialPerson{ Age: v }
		},
		"PartialPerson.Age",
	)
	return PartialPersonPrisms {
		Name: _prismName,
		Age: _prismAge,
	}
}

// PersonLenses provides lenses for accessing fields of Person
type PersonLenses struct {
	// mandatory fields
	Name __lens.Lens[Person, NonEmptyString]
	Age __lens.Lens[Person, AdultAge]
	// optional fields
	NameO __lens_option.LensO[Person, NonEmptyString]
	AgeO __lens_option.LensO[Person, AdultAge]
}

// PersonRefLenses provides lenses for accessing fields of Person via a reference to Person
type PersonRefLenses struct {
	// mandatory fields
	Name __lens.Lens[*Person, NonEmptyString]
	Age __lens.Lens[*Person, AdultAge]
	// optional fields
	NameO __lens_option.LensO[*Person, NonEmptyString]
	AgeO __lens_option.LensO[*Person, AdultAge]
	// prisms
	NameP __prism.Prism[*Person, NonEmptyString]
	AgeP __prism.Prism[*Person, AdultAge]
}

// PersonPrisms provides prisms for accessing fields of Person
type PersonPrisms struct {
	Name __prism.Prism[Person, NonEmptyString]
	Age __prism.Prism[Person, AdultAge]
}

// MakePersonLenses creates a new PersonLenses with lenses for all fields
func MakePersonLenses() PersonLenses {
	// mandatory lenses
	lensName := __lens.MakeLensWithName(
		func(s Person) NonEmptyString { return s.Name },
		func(s Person, v NonEmptyString) Person { s.Name = v; return s },
		"Person.Name",
	)
	lensAge := __lens.MakeLensWithName(
		func(s Person) AdultAge { return s.Age },
		func(s Person, v AdultAge) Person { s.Age = v; return s },
		"Person.Age",
	)
	// optional lenses
	lensNameO := __lens_option.FromIso[Person](__iso_option.FromZero[NonEmptyString]())(lensName)
	lensAgeO := __lens_option.FromIso[Person](__iso_option.FromZero[AdultAge]())(lensAge)
	return PersonLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
	}
}

// MakePersonRefLenses creates a new PersonRefLenses with lenses for all fields
func MakePersonRefLenses() PersonRefLenses {
	// mandatory lenses
	lensName := __lens.MakeLensStrictWithName(
		func(s *Person) NonEmptyString { return s.Name },
		func(s *Person, v NonEmptyString) *Person { s.Name = v; return s },
		"(*Person).Name",
	)
	lensAge := __lens.MakeLensStrictWithName(
		func(s *Person) AdultAge { return s.Age },
		func(s *Person, v AdultAge) *Person { s.Age = v; return s },
		"(*Person).Age",
	)
	// optional lenses
	lensNameO := __lens_option.FromIso[*Person](__iso_option.FromZero[NonEmptyString]())(lensName)
	lensAgeO := __lens_option.FromIso[*Person](__iso_option.FromZero[AdultAge]())(lensAge)
	return PersonRefLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
	}
}

// MakePersonPrisms creates a new PersonPrisms with prisms for all fields
func MakePersonPrisms() PersonPrisms {
	_fromNonZeroName := __option.FromNonZero[NonEmptyString]()
	_prismName := __prism.MakePrismWithName(
		func(s Person) __option.Option[NonEmptyString] { return _fromNonZeroName(s.Name) },
		func(v NonEmptyString) Person {
			return Person{ Name: v }
		},
		"Person.Name",
	)
	_fromNonZeroAge := __option.FromNonZero[AdultAge]()
	_prismAge := __prism.MakePrismWithName(
		func(s Person) __option.Option[AdultAge] { return _fromNonZeroAge(s.Age) },
		func(v AdultAge) Person {
			return Person{ Age: v }
		},
		"Person.Age",
	)
	return PersonPrisms {
		Name: _prismName,
		Age: _prismAge,
	}
}
