package lens

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-12-16 10:19:47.031145 +0100 CET m=+0.004763401

import (
	L "github.com/IBM/fp-go/v2/optics/lens"
	LO "github.com/IBM/fp-go/v2/optics/lens/option"
	IO "github.com/IBM/fp-go/v2/optics/iso/option"
	option "github.com/IBM/fp-go/v2/optics/lens/option"
)

// PersonLenses provides lenses for accessing fields of Person
type PersonLenses struct {
	// mandatory fields
	Name L.Lens[Person, string]
	Age L.Lens[Person, int]
	Email L.Lens[Person, string]
	Phone L.Lens[Person, *string]
	// optional fields
	NameO LO.LensO[Person, string]
	AgeO LO.LensO[Person, int]
	EmailO LO.LensO[Person, string]
	PhoneO LO.LensO[Person, *string]
}

// PersonRefLenses provides lenses for accessing fields of Person via a reference to Person
type PersonRefLenses struct {
	// mandatory fields
	Name L.Lens[*Person, string]
	Age L.Lens[*Person, int]
	Email L.Lens[*Person, string]
	Phone L.Lens[*Person, *string]
	// optional fields
	NameO LO.LensO[*Person, string]
	AgeO LO.LensO[*Person, int]
	EmailO LO.LensO[*Person, string]
	PhoneO LO.LensO[*Person, *string]
}

// MakePersonLenses creates a new PersonLenses with lenses for all fields
func MakePersonLenses() PersonLenses {
	// mandatory lenses
	lensName := L.MakeLensWithName(
		func(s Person) string { return s.Name },
		func(s Person, v string) Person { s.Name = v; return s },
		"Person.Name",
	)
	lensAge := L.MakeLensWithName(
		func(s Person) int { return s.Age },
		func(s Person, v int) Person { s.Age = v; return s },
		"Person.Age",
	)
	lensEmail := L.MakeLensWithName(
		func(s Person) string { return s.Email },
		func(s Person, v string) Person { s.Email = v; return s },
		"Person.Email",
	)
	lensPhone := L.MakeLensWithName(
		func(s Person) *string { return s.Phone },
		func(s Person, v *string) Person { s.Phone = v; return s },
		"Person.Phone",
	)
	// optional lenses
	lensNameO := LO.FromIso[Person](IO.FromZero[string]())(lensName)
	lensAgeO := LO.FromIso[Person](IO.FromZero[int]())(lensAge)
	lensEmailO := LO.FromIso[Person](IO.FromZero[string]())(lensEmail)
	lensPhoneO := LO.FromIso[Person](IO.FromZero[*string]())(lensPhone)
	return PersonLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		Email: lensEmail,
		Phone: lensPhone,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
		EmailO: lensEmailO,
		PhoneO: lensPhoneO,
	}
}

// MakePersonRefLenses creates a new PersonRefLenses with lenses for all fields
func MakePersonRefLenses() PersonRefLenses {
	// mandatory lenses
	lensName := L.MakeLensStrictWithName(
		func(s *Person) string { return s.Name },
		func(s *Person, v string) *Person { s.Name = v; return s },
		"(*Person).Name",
	)
	lensAge := L.MakeLensStrictWithName(
		func(s *Person) int { return s.Age },
		func(s *Person, v int) *Person { s.Age = v; return s },
		"(*Person).Age",
	)
	lensEmail := L.MakeLensStrictWithName(
		func(s *Person) string { return s.Email },
		func(s *Person, v string) *Person { s.Email = v; return s },
		"(*Person).Email",
	)
	lensPhone := L.MakeLensStrictWithName(
		func(s *Person) *string { return s.Phone },
		func(s *Person, v *string) *Person { s.Phone = v; return s },
		"(*Person).Phone",
	)
	// optional lenses
	lensNameO := LO.FromIso[*Person](IO.FromZero[string]())(lensName)
	lensAgeO := LO.FromIso[*Person](IO.FromZero[int]())(lensAge)
	lensEmailO := LO.FromIso[*Person](IO.FromZero[string]())(lensEmail)
	lensPhoneO := LO.FromIso[*Person](IO.FromZero[*string]())(lensPhone)
	return PersonRefLenses{
		// mandatory lenses
		Name: lensName,
		Age: lensAge,
		Email: lensEmail,
		Phone: lensPhone,
		// optional lenses
		NameO: lensNameO,
		AgeO: lensAgeO,
		EmailO: lensEmailO,
		PhoneO: lensPhoneO,
	}
}

// AddressLenses provides lenses for accessing fields of Address
type AddressLenses struct {
	// mandatory fields
	Street L.Lens[Address, string]
	City L.Lens[Address, string]
	ZipCode L.Lens[Address, string]
	Country L.Lens[Address, string]
	State L.Lens[Address, *string]
	// optional fields
	StreetO LO.LensO[Address, string]
	CityO LO.LensO[Address, string]
	ZipCodeO LO.LensO[Address, string]
	CountryO LO.LensO[Address, string]
	StateO LO.LensO[Address, *string]
}

// AddressRefLenses provides lenses for accessing fields of Address via a reference to Address
type AddressRefLenses struct {
	// mandatory fields
	Street L.Lens[*Address, string]
	City L.Lens[*Address, string]
	ZipCode L.Lens[*Address, string]
	Country L.Lens[*Address, string]
	State L.Lens[*Address, *string]
	// optional fields
	StreetO LO.LensO[*Address, string]
	CityO LO.LensO[*Address, string]
	ZipCodeO LO.LensO[*Address, string]
	CountryO LO.LensO[*Address, string]
	StateO LO.LensO[*Address, *string]
}

// MakeAddressLenses creates a new AddressLenses with lenses for all fields
func MakeAddressLenses() AddressLenses {
	// mandatory lenses
	lensStreet := L.MakeLensWithName(
		func(s Address) string { return s.Street },
		func(s Address, v string) Address { s.Street = v; return s },
		"Address.Street",
	)
	lensCity := L.MakeLensWithName(
		func(s Address) string { return s.City },
		func(s Address, v string) Address { s.City = v; return s },
		"Address.City",
	)
	lensZipCode := L.MakeLensWithName(
		func(s Address) string { return s.ZipCode },
		func(s Address, v string) Address { s.ZipCode = v; return s },
		"Address.ZipCode",
	)
	lensCountry := L.MakeLensWithName(
		func(s Address) string { return s.Country },
		func(s Address, v string) Address { s.Country = v; return s },
		"Address.Country",
	)
	lensState := L.MakeLensWithName(
		func(s Address) *string { return s.State },
		func(s Address, v *string) Address { s.State = v; return s },
		"Address.State",
	)
	// optional lenses
	lensStreetO := LO.FromIso[Address](IO.FromZero[string]())(lensStreet)
	lensCityO := LO.FromIso[Address](IO.FromZero[string]())(lensCity)
	lensZipCodeO := LO.FromIso[Address](IO.FromZero[string]())(lensZipCode)
	lensCountryO := LO.FromIso[Address](IO.FromZero[string]())(lensCountry)
	lensStateO := LO.FromIso[Address](IO.FromZero[*string]())(lensState)
	return AddressLenses{
		// mandatory lenses
		Street: lensStreet,
		City: lensCity,
		ZipCode: lensZipCode,
		Country: lensCountry,
		State: lensState,
		// optional lenses
		StreetO: lensStreetO,
		CityO: lensCityO,
		ZipCodeO: lensZipCodeO,
		CountryO: lensCountryO,
		StateO: lensStateO,
	}
}

// MakeAddressRefLenses creates a new AddressRefLenses with lenses for all fields
func MakeAddressRefLenses() AddressRefLenses {
	// mandatory lenses
	lensStreet := L.MakeLensStrictWithName(
		func(s *Address) string { return s.Street },
		func(s *Address, v string) *Address { s.Street = v; return s },
		"(*Address).Street",
	)
	lensCity := L.MakeLensStrictWithName(
		func(s *Address) string { return s.City },
		func(s *Address, v string) *Address { s.City = v; return s },
		"(*Address).City",
	)
	lensZipCode := L.MakeLensStrictWithName(
		func(s *Address) string { return s.ZipCode },
		func(s *Address, v string) *Address { s.ZipCode = v; return s },
		"(*Address).ZipCode",
	)
	lensCountry := L.MakeLensStrictWithName(
		func(s *Address) string { return s.Country },
		func(s *Address, v string) *Address { s.Country = v; return s },
		"(*Address).Country",
	)
	lensState := L.MakeLensStrictWithName(
		func(s *Address) *string { return s.State },
		func(s *Address, v *string) *Address { s.State = v; return s },
		"(*Address).State",
	)
	// optional lenses
	lensStreetO := LO.FromIso[*Address](IO.FromZero[string]())(lensStreet)
	lensCityO := LO.FromIso[*Address](IO.FromZero[string]())(lensCity)
	lensZipCodeO := LO.FromIso[*Address](IO.FromZero[string]())(lensZipCode)
	lensCountryO := LO.FromIso[*Address](IO.FromZero[string]())(lensCountry)
	lensStateO := LO.FromIso[*Address](IO.FromZero[*string]())(lensState)
	return AddressRefLenses{
		// mandatory lenses
		Street: lensStreet,
		City: lensCity,
		ZipCode: lensZipCode,
		Country: lensCountry,
		State: lensState,
		// optional lenses
		StreetO: lensStreetO,
		CityO: lensCityO,
		ZipCodeO: lensZipCodeO,
		CountryO: lensCountryO,
		StateO: lensStateO,
	}
}

// CompanyLenses provides lenses for accessing fields of Company
type CompanyLenses struct {
	// mandatory fields
	Name L.Lens[Company, string]
	Address L.Lens[Company, Address]
	CEO L.Lens[Company, Person]
	Website L.Lens[Company, *string]
	// optional fields
	NameO LO.LensO[Company, string]
	AddressO LO.LensO[Company, Address]
	CEOO LO.LensO[Company, Person]
	WebsiteO LO.LensO[Company, *string]
}

// CompanyRefLenses provides lenses for accessing fields of Company via a reference to Company
type CompanyRefLenses struct {
	// mandatory fields
	Name L.Lens[*Company, string]
	Address L.Lens[*Company, Address]
	CEO L.Lens[*Company, Person]
	Website L.Lens[*Company, *string]
	// optional fields
	NameO LO.LensO[*Company, string]
	AddressO LO.LensO[*Company, Address]
	CEOO LO.LensO[*Company, Person]
	WebsiteO LO.LensO[*Company, *string]
}

// MakeCompanyLenses creates a new CompanyLenses with lenses for all fields
func MakeCompanyLenses() CompanyLenses {
	// mandatory lenses
	lensName := L.MakeLensWithName(
		func(s Company) string { return s.Name },
		func(s Company, v string) Company { s.Name = v; return s },
		"Company.Name",
	)
	lensAddress := L.MakeLensWithName(
		func(s Company) Address { return s.Address },
		func(s Company, v Address) Company { s.Address = v; return s },
		"Company.Address",
	)
	lensCEO := L.MakeLensWithName(
		func(s Company) Person { return s.CEO },
		func(s Company, v Person) Company { s.CEO = v; return s },
		"Company.CEO",
	)
	lensWebsite := L.MakeLensWithName(
		func(s Company) *string { return s.Website },
		func(s Company, v *string) Company { s.Website = v; return s },
		"Company.Website",
	)
	// optional lenses
	lensNameO := LO.FromIso[Company](IO.FromZero[string]())(lensName)
	lensAddressO := LO.FromIso[Company](IO.FromZero[Address]())(lensAddress)
	lensCEOO := LO.FromIso[Company](IO.FromZero[Person]())(lensCEO)
	lensWebsiteO := LO.FromIso[Company](IO.FromZero[*string]())(lensWebsite)
	return CompanyLenses{
		// mandatory lenses
		Name: lensName,
		Address: lensAddress,
		CEO: lensCEO,
		Website: lensWebsite,
		// optional lenses
		NameO: lensNameO,
		AddressO: lensAddressO,
		CEOO: lensCEOO,
		WebsiteO: lensWebsiteO,
	}
}

// MakeCompanyRefLenses creates a new CompanyRefLenses with lenses for all fields
func MakeCompanyRefLenses() CompanyRefLenses {
	// mandatory lenses
	lensName := L.MakeLensStrictWithName(
		func(s *Company) string { return s.Name },
		func(s *Company, v string) *Company { s.Name = v; return s },
		"(*Company).Name",
	)
	lensAddress := L.MakeLensStrictWithName(
		func(s *Company) Address { return s.Address },
		func(s *Company, v Address) *Company { s.Address = v; return s },
		"(*Company).Address",
	)
	lensCEO := L.MakeLensStrictWithName(
		func(s *Company) Person { return s.CEO },
		func(s *Company, v Person) *Company { s.CEO = v; return s },
		"(*Company).CEO",
	)
	lensWebsite := L.MakeLensStrictWithName(
		func(s *Company) *string { return s.Website },
		func(s *Company, v *string) *Company { s.Website = v; return s },
		"(*Company).Website",
	)
	// optional lenses
	lensNameO := LO.FromIso[*Company](IO.FromZero[string]())(lensName)
	lensAddressO := LO.FromIso[*Company](IO.FromZero[Address]())(lensAddress)
	lensCEOO := LO.FromIso[*Company](IO.FromZero[Person]())(lensCEO)
	lensWebsiteO := LO.FromIso[*Company](IO.FromZero[*string]())(lensWebsite)
	return CompanyRefLenses{
		// mandatory lenses
		Name: lensName,
		Address: lensAddress,
		CEO: lensCEO,
		Website: lensWebsite,
		// optional lenses
		NameO: lensNameO,
		AddressO: lensAddressO,
		CEOO: lensCEOO,
		WebsiteO: lensWebsiteO,
	}
}

// CompanyExtendedLenses provides lenses for accessing fields of CompanyExtended
type CompanyExtendedLenses struct {
	// mandatory fields
	Name L.Lens[CompanyExtended, string]
	Address L.Lens[CompanyExtended, Address]
	CEO L.Lens[CompanyExtended, Person]
	Website L.Lens[CompanyExtended, *string]
	Extended L.Lens[CompanyExtended, string]
	// optional fields
	NameO LO.LensO[CompanyExtended, string]
	AddressO LO.LensO[CompanyExtended, Address]
	CEOO LO.LensO[CompanyExtended, Person]
	WebsiteO LO.LensO[CompanyExtended, *string]
	ExtendedO LO.LensO[CompanyExtended, string]
}

// CompanyExtendedRefLenses provides lenses for accessing fields of CompanyExtended via a reference to CompanyExtended
type CompanyExtendedRefLenses struct {
	// mandatory fields
	Name L.Lens[*CompanyExtended, string]
	Address L.Lens[*CompanyExtended, Address]
	CEO L.Lens[*CompanyExtended, Person]
	Website L.Lens[*CompanyExtended, *string]
	Extended L.Lens[*CompanyExtended, string]
	// optional fields
	NameO LO.LensO[*CompanyExtended, string]
	AddressO LO.LensO[*CompanyExtended, Address]
	CEOO LO.LensO[*CompanyExtended, Person]
	WebsiteO LO.LensO[*CompanyExtended, *string]
	ExtendedO LO.LensO[*CompanyExtended, string]
}

// MakeCompanyExtendedLenses creates a new CompanyExtendedLenses with lenses for all fields
func MakeCompanyExtendedLenses() CompanyExtendedLenses {
	// mandatory lenses
	lensName := L.MakeLensWithName(
		func(s CompanyExtended) string { return s.Name },
		func(s CompanyExtended, v string) CompanyExtended { s.Name = v; return s },
		"CompanyExtended.Name",
	)
	lensAddress := L.MakeLensWithName(
		func(s CompanyExtended) Address { return s.Address },
		func(s CompanyExtended, v Address) CompanyExtended { s.Address = v; return s },
		"CompanyExtended.Address",
	)
	lensCEO := L.MakeLensWithName(
		func(s CompanyExtended) Person { return s.CEO },
		func(s CompanyExtended, v Person) CompanyExtended { s.CEO = v; return s },
		"CompanyExtended.CEO",
	)
	lensWebsite := L.MakeLensWithName(
		func(s CompanyExtended) *string { return s.Website },
		func(s CompanyExtended, v *string) CompanyExtended { s.Website = v; return s },
		"CompanyExtended.Website",
	)
	lensExtended := L.MakeLensWithName(
		func(s CompanyExtended) string { return s.Extended },
		func(s CompanyExtended, v string) CompanyExtended { s.Extended = v; return s },
		"CompanyExtended.Extended",
	)
	// optional lenses
	lensNameO := LO.FromIso[CompanyExtended](IO.FromZero[string]())(lensName)
	lensAddressO := LO.FromIso[CompanyExtended](IO.FromZero[Address]())(lensAddress)
	lensCEOO := LO.FromIso[CompanyExtended](IO.FromZero[Person]())(lensCEO)
	lensWebsiteO := LO.FromIso[CompanyExtended](IO.FromZero[*string]())(lensWebsite)
	lensExtendedO := LO.FromIso[CompanyExtended](IO.FromZero[string]())(lensExtended)
	return CompanyExtendedLenses{
		// mandatory lenses
		Name: lensName,
		Address: lensAddress,
		CEO: lensCEO,
		Website: lensWebsite,
		Extended: lensExtended,
		// optional lenses
		NameO: lensNameO,
		AddressO: lensAddressO,
		CEOO: lensCEOO,
		WebsiteO: lensWebsiteO,
		ExtendedO: lensExtendedO,
	}
}

// MakeCompanyExtendedRefLenses creates a new CompanyExtendedRefLenses with lenses for all fields
func MakeCompanyExtendedRefLenses() CompanyExtendedRefLenses {
	// mandatory lenses
	lensName := L.MakeLensStrictWithName(
		func(s *CompanyExtended) string { return s.Name },
		func(s *CompanyExtended, v string) *CompanyExtended { s.Name = v; return s },
		"(*CompanyExtended).Name",
	)
	lensAddress := L.MakeLensStrictWithName(
		func(s *CompanyExtended) Address { return s.Address },
		func(s *CompanyExtended, v Address) *CompanyExtended { s.Address = v; return s },
		"(*CompanyExtended).Address",
	)
	lensCEO := L.MakeLensStrictWithName(
		func(s *CompanyExtended) Person { return s.CEO },
		func(s *CompanyExtended, v Person) *CompanyExtended { s.CEO = v; return s },
		"(*CompanyExtended).CEO",
	)
	lensWebsite := L.MakeLensStrictWithName(
		func(s *CompanyExtended) *string { return s.Website },
		func(s *CompanyExtended, v *string) *CompanyExtended { s.Website = v; return s },
		"(*CompanyExtended).Website",
	)
	lensExtended := L.MakeLensStrictWithName(
		func(s *CompanyExtended) string { return s.Extended },
		func(s *CompanyExtended, v string) *CompanyExtended { s.Extended = v; return s },
		"(*CompanyExtended).Extended",
	)
	// optional lenses
	lensNameO := LO.FromIso[*CompanyExtended](IO.FromZero[string]())(lensName)
	lensAddressO := LO.FromIso[*CompanyExtended](IO.FromZero[Address]())(lensAddress)
	lensCEOO := LO.FromIso[*CompanyExtended](IO.FromZero[Person]())(lensCEO)
	lensWebsiteO := LO.FromIso[*CompanyExtended](IO.FromZero[*string]())(lensWebsite)
	lensExtendedO := LO.FromIso[*CompanyExtended](IO.FromZero[string]())(lensExtended)
	return CompanyExtendedRefLenses{
		// mandatory lenses
		Name: lensName,
		Address: lensAddress,
		CEO: lensCEO,
		Website: lensWebsite,
		Extended: lensExtended,
		// optional lenses
		NameO: lensNameO,
		AddressO: lensAddressO,
		CEOO: lensCEOO,
		WebsiteO: lensWebsiteO,
		ExtendedO: lensExtendedO,
	}
}

// CheckOptionLenses provides lenses for accessing fields of CheckOption
type CheckOptionLenses struct {
	// mandatory fields
	Name L.Lens[CheckOption, option.Option[string]]
	Value L.Lens[CheckOption, string]
	// optional fields
	ValueO LO.LensO[CheckOption, string]
}

// CheckOptionRefLenses provides lenses for accessing fields of CheckOption via a reference to CheckOption
type CheckOptionRefLenses struct {
	// mandatory fields
	Name L.Lens[*CheckOption, option.Option[string]]
	Value L.Lens[*CheckOption, string]
	// optional fields
	ValueO LO.LensO[*CheckOption, string]
}

// MakeCheckOptionLenses creates a new CheckOptionLenses with lenses for all fields
func MakeCheckOptionLenses() CheckOptionLenses {
	// mandatory lenses
	lensName := L.MakeLensWithName(
		func(s CheckOption) option.Option[string] { return s.Name },
		func(s CheckOption, v option.Option[string]) CheckOption { s.Name = v; return s },
		"CheckOption.Name",
	)
	lensValue := L.MakeLensWithName(
		func(s CheckOption) string { return s.Value },
		func(s CheckOption, v string) CheckOption { s.Value = v; return s },
		"CheckOption.Value",
	)
	// optional lenses
	lensValueO := LO.FromIso[CheckOption](IO.FromZero[string]())(lensValue)
	return CheckOptionLenses{
		// mandatory lenses
		Name: lensName,
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// MakeCheckOptionRefLenses creates a new CheckOptionRefLenses with lenses for all fields
func MakeCheckOptionRefLenses() CheckOptionRefLenses {
	// mandatory lenses
	lensName := L.MakeLensRefWithName(
		func(s *CheckOption) option.Option[string] { return s.Name },
		func(s *CheckOption, v option.Option[string]) *CheckOption { s.Name = v; return s },
		"(*CheckOption).Name",
	)
	lensValue := L.MakeLensStrictWithName(
		func(s *CheckOption) string { return s.Value },
		func(s *CheckOption, v string) *CheckOption { s.Value = v; return s },
		"(*CheckOption).Value",
	)
	// optional lenses
	lensValueO := LO.FromIso[*CheckOption](IO.FromZero[string]())(lensValue)
	return CheckOptionRefLenses{
		// mandatory lenses
		Name: lensName,
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// WithGenericLenses provides lenses for accessing fields of WithGeneric
type WithGenericLenses[T any] struct {
	// mandatory fields
	Name L.Lens[WithGeneric[T], string]
	Value L.Lens[WithGeneric[T], T]
	// optional fields
	NameO LO.LensO[WithGeneric[T], string]
}

// WithGenericRefLenses provides lenses for accessing fields of WithGeneric via a reference to WithGeneric
type WithGenericRefLenses[T any] struct {
	// mandatory fields
	Name L.Lens[*WithGeneric[T], string]
	Value L.Lens[*WithGeneric[T], T]
	// optional fields
	NameO LO.LensO[*WithGeneric[T], string]
}

// MakeWithGenericLenses creates a new WithGenericLenses with lenses for all fields
func MakeWithGenericLenses[T any]() WithGenericLenses[T] {
	// mandatory lenses
	lensName := L.MakeLensWithName(
		func(s WithGeneric[T]) string { return s.Name },
		func(s WithGeneric[T], v string) WithGeneric[T] { s.Name = v; return s },
		"WithGeneric[T].Name",
	)
	lensValue := L.MakeLensWithName(
		func(s WithGeneric[T]) T { return s.Value },
		func(s WithGeneric[T], v T) WithGeneric[T] { s.Value = v; return s },
		"WithGeneric[T].Value",
	)
	// optional lenses
	lensNameO := LO.FromIso[WithGeneric[T]](IO.FromZero[string]())(lensName)
	return WithGenericLenses[T]{
		// mandatory lenses
		Name: lensName,
		Value: lensValue,
		// optional lenses
		NameO: lensNameO,
	}
}

// MakeWithGenericRefLenses creates a new WithGenericRefLenses with lenses for all fields
func MakeWithGenericRefLenses[T any]() WithGenericRefLenses[T] {
	// mandatory lenses
	lensName := L.MakeLensStrictWithName(
		func(s *WithGeneric[T]) string { return s.Name },
		func(s *WithGeneric[T], v string) *WithGeneric[T] { s.Name = v; return s },
		"(*WithGeneric[T]).Name",
	)
	lensValue := L.MakeLensRefWithName(
		func(s *WithGeneric[T]) T { return s.Value },
		func(s *WithGeneric[T], v T) *WithGeneric[T] { s.Value = v; return s },
		"(*WithGeneric[T]).Value",
	)
	// optional lenses
	lensNameO := LO.FromIso[*WithGeneric[T]](IO.FromZero[string]())(lensName)
	return WithGenericRefLenses[T]{
		// mandatory lenses
		Name: lensName,
		Value: lensValue,
		// optional lenses
		NameO: lensNameO,
	}
}
