// Copyright (c) 2023 - 2025 IBM Corp.
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	A "github.com/IBM/fp-go/v2/array"
	C "github.com/urfave/cli/v3"
)

func nonGenericIOOption(param string) string {
	return fmt.Sprintf("IOOption[%s]", param)
}

func genericIOOption(param string) string {
	return fmt.Sprintf("func() O.Option[%s]", param)
}

var extrasIOOption = A.Empty[string]()

func generateIOOptionSequenceT(f *os.File, i int) {
	generateGenericSequenceT("", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericSequenceT("Seq", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericSequenceT("Par", nonGenericIOOption, extrasIOOption)(f, i)
}

func generateIOOptionSequenceTuple(f *os.File, i int) {
	generateGenericSequenceTuple("", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericSequenceTuple("Seq", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericSequenceTuple("Par", nonGenericIOOption, extrasIOOption)(f, i)
}

func generateIOOptionTraverseTuple(f *os.File, i int) {
	generateGenericTraverseTuple("", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericTraverseTuple("Seq", nonGenericIOOption, extrasIOOption)(f, i)
	generateGenericTraverseTuple("Par", nonGenericIOOption, extrasIOOption)(f, i)
}

func generateIOOptionHelpers(filename string, count int) error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	pkg := filepath.Base(absDir)
	f, err := os.Create(filepath.Clean(filename))
	if err != nil {
		return err
	}
	defer f.Close()

	// log
	log.Printf("Generating code in [%s] for package [%s] with [%d] repetitions ...", filename, pkg, count)

	// some header
	fmt.Fprintln(f, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(f, "// This file was generated by robots at")
	fmt.Fprintf(f, "// %s\n\n", time.Now())

	fmt.Fprintf(f, "package %s\n\n", pkg)

	fmt.Fprintf(f, `
import (
	"github.com/IBM/fp-go/v2/tuple"
	"github.com/IBM/fp-go/v2/internal/apply"
)
`)

	for i := 1; i <= count; i++ {
		// sequenceT
		generateIOOptionSequenceT(f, i)
		// sequenceTuple
		generateIOOptionSequenceTuple(f, i)
		// traverseTuple
		generateIOOptionTraverseTuple(f, i)
	}

	return nil
}

func IOOptionCommand() *C.Command {
	return &C.Command{
		Name:  "iooption",
		Usage: "generate code for IOOption",
		Flags: []C.Flag{
			flagCount,
			flagFilename,
		},
		Action: func(ctx context.Context, cmd *C.Command) error {
			return generateIOOptionHelpers(
				cmd.String(keyFilename),
				cmd.Int(keyCount),
			)
		},
	}
}
