package cli

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	C "github.com/urfave/cli/v2"
)

func eitherHKT(typeE string) func(typeA string) string {
	return func(typeA string) string {
		return fmt.Sprintf("Either[%s, %s]", typeE, typeA)
	}
}

func generateEitherTraverseTuple(f *os.File, i int) {
	generateTraverseTuple1(eitherHKT("E"), "E")(f, i)
}

func generateEitherSequenceTuple(f *os.File, i int) {
	generateSequenceTuple1(eitherHKT("E"), "E")(f, i)
}

func generateEitherSequenceT(f *os.File, i int) {

	tuple := tupleType(i)

	fmt.Fprintf(f, "\n// SequenceT%d converts %d parameters of [Either[E, T]] into an [Either] of a [Tuple%d].\n", i, i, i)
	fmt.Fprintf(f, "func SequenceT%d[E", i)
	for j := 0; j < i; j++ {
		fmt.Fprintf(f, ", T%d", j+1)
	}
	fmt.Fprintf(f, " any](")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "t%d Either[E, T%d]", j+1, j+1)
	}
	fmt.Fprintf(f, ") Either[E, %s] {\n", tuple)
	fmt.Fprintf(f, "  return A.SequenceT%d(\n", i)
	// map
	fmt.Fprintf(f, "    Map[E, T1,")
	for j := 1; j < i; j++ {
		fmt.Fprintf(f, " func(T%d)", j+1)
	}
	fmt.Fprintf(f, " %s],\n", tuple)
	// applicatives
	for j := 1; j < i; j++ {
		fmt.Fprintf(f, "    Ap[")
		for k := j + 1; k < i; k++ {
			if k > j+1 {
				fmt.Fprintf(f, " ")
			}
			fmt.Fprintf(f, "func(T%d)", k+1)
		}
		if j < i-1 {
			fmt.Fprintf(f, " ")
		}
		fmt.Fprintf(f, "%s, E, T%d],\n", tuple, j+1)
	}
	for j := 0; j < i; j++ {
		fmt.Fprintf(f, "    t%d,\n", j+1)
	}
	fmt.Fprintf(f, "  )\n")
	fmt.Fprintf(f, "}\n")
}

func generateUneitherize(f *os.File, i int) {
	// Create the optionize version
	fmt.Fprintf(f, "\n// Uneitherize%d converts a function with %d parameters returning an Either into a function with %d parameters returning a tuple\n// The inverse function is [Eitherize%d]\n", i, i, i, i)
	fmt.Fprintf(f, "func Uneitherize%d[F ~func(", i)
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "T%d", j)
	}
	fmt.Fprintf(f, ") Either[error, R]")
	for j := 0; j < i; j++ {
		fmt.Fprintf(f, ", T%d", j)
	}
	fmt.Fprintf(f, ", R any](f F) func(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "T%d", j)
	}
	fmt.Fprintf(f, ") (R, error) {\n")
	fmt.Fprintf(f, "  return func(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "t%d T%d", j, j)
	}
	fmt.Fprintf(f, ") (R, error) {\n")
	fmt.Fprintf(f, "    return UnwrapError(f(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "t%d", j)
	}
	fmt.Fprintln(f, "))")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "}")
}

func generateEitherize(f *os.File, i int) {
	// Create the optionize version
	fmt.Fprintf(f, "\n// Eitherize%d converts a function with %d parameters returning a tuple into a function with %d parameters returning an Either\n// The inverse function is [Uneitherize%d]\n", i, i, i, i)
	fmt.Fprintf(f, "func Eitherize%d[F ~func(", i)
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "T%d", j)
	}
	fmt.Fprintf(f, ") (R, error)")
	for j := 0; j < i; j++ {
		fmt.Fprintf(f, ", T%d", j)
	}
	fmt.Fprintf(f, ", R any](f F) func(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "T%d", j)
	}
	fmt.Fprintf(f, ") Either[error, R] {\n")
	fmt.Fprintf(f, "  return func(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "t%d T%d", j, j)
	}
	fmt.Fprintf(f, ") Either[error, R] {\n")
	fmt.Fprintf(f, "    return TryCatchError(func() (R, error) {\n")
	fmt.Fprintf(f, "      return f(")
	for j := 0; j < i; j++ {
		if j > 0 {
			fmt.Fprintf(f, ", ")
		}
		fmt.Fprintf(f, "t%d", j)
	}
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f, "    })")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "}")
}

func generateEitherHelpers(filename string, count int) error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	pkg := filepath.Base(absDir)
	f, err := os.Create(filepath.Clean(filename))
	if err != nil {
		return err
	}
	defer f.Close()
	// log
	log.Printf("Generating code in [%s] for package [%s] with [%d] repetitions ...", filename, pkg, count)

	// some header
	fmt.Fprintln(f, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(f, "// This file was generated by robots at")
	fmt.Fprintf(f, "// %s\n", time.Now())

	fmt.Fprintf(f, "package %s\n\n", pkg)

	fmt.Fprintf(f, `
import (
	A "github.com/ibm/fp-go/internal/apply"
	T "github.com/ibm/fp-go/tuple"
)
`)

	// zero level functions

	// optionize
	generateEitherize(f, 0)
	// unoptionize
	generateUneitherize(f, 0)

	for i := 1; i <= count; i++ {
		// optionize
		generateEitherize(f, i)
		// unoptionize
		generateUneitherize(f, i)
		// sequenceT
		generateEitherSequenceT(f, i)
		// sequenceTuple
		generateEitherSequenceTuple(f, i)
		// traverseTuple
		generateEitherTraverseTuple(f, i)
	}

	return nil
}

func EitherCommand() *C.Command {
	return &C.Command{
		Name:  "either",
		Usage: "generate code for Either",
		Flags: []C.Flag{
			flagCount,
			flagFilename,
		},
		Action: func(ctx *C.Context) error {
			return generateEitherHelpers(
				ctx.String(keyFilename),
				ctx.Int(keyCount),
			)
		},
	}
}
