package lenses

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2026-01-27 16:08:47.5483589 +0100 CET m=+0.003380301

import (
	url "net/url"

	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
)

// ErrorLenses provides lenses for accessing fields of url.Error
type ErrorLenses struct {
	// mandatory fields
	Op  __lens.Lens[url.Error, string]
	URL __lens.Lens[url.Error, string]
	Err __lens.Lens[url.Error, error]
	// optional fields
	OpO  __lens_option.LensO[url.Error, string]
	URLO __lens_option.LensO[url.Error, string]
	ErrO __lens_option.LensO[url.Error, error]
}

// ErrorRefLenses provides lenses for accessing fields of url.Error via a reference to url.Error
type ErrorRefLenses struct {
	// mandatory fields
	Op  __lens.Lens[*url.Error, string]
	URL __lens.Lens[*url.Error, string]
	Err __lens.Lens[*url.Error, error]
	// optional fields
	OpO  __lens_option.LensO[*url.Error, string]
	URLO __lens_option.LensO[*url.Error, string]
	ErrO __lens_option.LensO[*url.Error, error]
	// prisms
	OpP  __prism.Prism[*url.Error, string]
	URLP __prism.Prism[*url.Error, string]
	ErrP __prism.Prism[*url.Error, error]
}

// ErrorPrisms provides prisms for accessing fields of url.Error
type ErrorPrisms struct {
	Op  __prism.Prism[url.Error, string]
	URL __prism.Prism[url.Error, string]
	Err __prism.Prism[url.Error, error]
}

// MakeErrorLenses creates a new ErrorLenses with lenses for all fields
func MakeErrorLenses() ErrorLenses {
	// mandatory lenses
	lensOp := __lens.MakeLensWithName(
		func(s url.Error) string { return s.Op },
		func(s url.Error, v string) url.Error { s.Op = v; return s },
		"Error.Op",
	)
	lensURL := __lens.MakeLensWithName(
		func(s url.Error) string { return s.URL },
		func(s url.Error, v string) url.Error { s.URL = v; return s },
		"Error.URL",
	)
	lensErr := __lens.MakeLensWithName(
		func(s url.Error) error { return s.Err },
		func(s url.Error, v error) url.Error { s.Err = v; return s },
		"Error.Err",
	)
	// optional lenses
	lensOpO := __lens_option.FromIso[url.Error](__iso_option.FromZero[string]())(lensOp)
	lensURLO := __lens_option.FromIso[url.Error](__iso_option.FromZero[string]())(lensURL)
	lensErrO := __lens_option.FromIso[url.Error](__iso_option.FromZero[error]())(lensErr)
	return ErrorLenses{
		// mandatory lenses
		Op:  lensOp,
		URL: lensURL,
		Err: lensErr,
		// optional lenses
		OpO:  lensOpO,
		URLO: lensURLO,
		ErrO: lensErrO,
	}
}

// MakeErrorRefLenses creates a new ErrorRefLenses with lenses for all fields
func MakeErrorRefLenses() ErrorRefLenses {
	// mandatory lenses
	lensOp := __lens.MakeLensStrictWithName(
		func(s *url.Error) string { return s.Op },
		func(s *url.Error, v string) *url.Error { s.Op = v; return s },
		"(*url.Error).Op",
	)
	lensURL := __lens.MakeLensStrictWithName(
		func(s *url.Error) string { return s.URL },
		func(s *url.Error, v string) *url.Error { s.URL = v; return s },
		"(*url.Error).url.URL",
	)
	lensErr := __lens.MakeLensStrictWithName(
		func(s *url.Error) error { return s.Err },
		func(s *url.Error, v error) *url.Error { s.Err = v; return s },
		"(*url.Error).Err",
	)
	// optional lenses
	lensOpO := __lens_option.FromIso[*url.Error](__iso_option.FromZero[string]())(lensOp)
	lensURLO := __lens_option.FromIso[*url.Error](__iso_option.FromZero[string]())(lensURL)
	lensErrO := __lens_option.FromIso[*url.Error](__iso_option.FromZero[error]())(lensErr)
	return ErrorRefLenses{
		// mandatory lenses
		Op:  lensOp,
		URL: lensURL,
		Err: lensErr,
		// optional lenses
		OpO:  lensOpO,
		URLO: lensURLO,
		ErrO: lensErrO,
	}
}

// MakeErrorPrisms creates a new ErrorPrisms with prisms for all fields
func MakeErrorPrisms() ErrorPrisms {
	_fromNonZeroOp := __option.FromNonZero[string]()
	_prismOp := __prism.MakePrismWithName(
		func(s url.Error) __option.Option[string] { return _fromNonZeroOp(s.Op) },
		func(v string) url.Error {
			return url.Error{Op: v}
		},
		"Error.Op",
	)
	_fromNonZeroURL := __option.FromNonZero[string]()
	_prismURL := __prism.MakePrismWithName(
		func(s url.Error) __option.Option[string] { return _fromNonZeroURL(s.URL) },
		func(v string) url.Error {
			return url.Error{URL: v}
		},
		"Error.URL",
	)
	_fromNonZeroErr := __option.FromNonZero[error]()
	_prismErr := __prism.MakePrismWithName(
		func(s url.Error) __option.Option[error] { return _fromNonZeroErr(s.Err) },
		func(v error) url.Error {
			return url.Error{Err: v}
		},
		"Error.Err",
	)
	return ErrorPrisms{
		Op:  _prismOp,
		URL: _prismURL,
		Err: _prismErr,
	}
}

// URLLenses provides lenses for accessing fields of url.URL
type URLLenses struct {
	// mandatory fields
	Scheme      __lens.Lens[url.URL, string]
	Opaque      __lens.Lens[url.URL, string]
	User        __lens.Lens[url.URL, *url.Userinfo]
	Host        __lens.Lens[url.URL, string]
	Path        __lens.Lens[url.URL, string]
	RawPath     __lens.Lens[url.URL, string]
	OmitHost    __lens.Lens[url.URL, bool]
	ForceQuery  __lens.Lens[url.URL, bool]
	RawQuery    __lens.Lens[url.URL, string]
	Fragment    __lens.Lens[url.URL, string]
	RawFragment __lens.Lens[url.URL, string]
	// optional fields
	SchemeO      __lens_option.LensO[url.URL, string]
	OpaqueO      __lens_option.LensO[url.URL, string]
	UserO        __lens_option.LensO[url.URL, *url.Userinfo]
	HostO        __lens_option.LensO[url.URL, string]
	PathO        __lens_option.LensO[url.URL, string]
	RawPathO     __lens_option.LensO[url.URL, string]
	OmitHostO    __lens_option.LensO[url.URL, bool]
	ForceQueryO  __lens_option.LensO[url.URL, bool]
	RawQueryO    __lens_option.LensO[url.URL, string]
	FragmentO    __lens_option.LensO[url.URL, string]
	RawFragmentO __lens_option.LensO[url.URL, string]
}

// URLRefLenses provides lenses for accessing fields of url.URL via a reference to url.URL
type URLRefLenses struct {
	// mandatory fields
	Scheme      __lens.Lens[*url.URL, string]
	Opaque      __lens.Lens[*url.URL, string]
	User        __lens.Lens[*url.URL, *url.Userinfo]
	Host        __lens.Lens[*url.URL, string]
	Path        __lens.Lens[*url.URL, string]
	RawPath     __lens.Lens[*url.URL, string]
	OmitHost    __lens.Lens[*url.URL, bool]
	ForceQuery  __lens.Lens[*url.URL, bool]
	RawQuery    __lens.Lens[*url.URL, string]
	Fragment    __lens.Lens[*url.URL, string]
	RawFragment __lens.Lens[*url.URL, string]
	// optional fields
	SchemeO      __lens_option.LensO[*url.URL, string]
	OpaqueO      __lens_option.LensO[*url.URL, string]
	UserO        __lens_option.LensO[*url.URL, *url.Userinfo]
	HostO        __lens_option.LensO[*url.URL, string]
	PathO        __lens_option.LensO[*url.URL, string]
	RawPathO     __lens_option.LensO[*url.URL, string]
	OmitHostO    __lens_option.LensO[*url.URL, bool]
	ForceQueryO  __lens_option.LensO[*url.URL, bool]
	RawQueryO    __lens_option.LensO[*url.URL, string]
	FragmentO    __lens_option.LensO[*url.URL, string]
	RawFragmentO __lens_option.LensO[*url.URL, string]
	// prisms
	SchemeP      __prism.Prism[*url.URL, string]
	OpaqueP      __prism.Prism[*url.URL, string]
	UserP        __prism.Prism[*url.URL, *url.Userinfo]
	HostP        __prism.Prism[*url.URL, string]
	PathP        __prism.Prism[*url.URL, string]
	RawPathP     __prism.Prism[*url.URL, string]
	OmitHostP    __prism.Prism[*url.URL, bool]
	ForceQueryP  __prism.Prism[*url.URL, bool]
	RawQueryP    __prism.Prism[*url.URL, string]
	FragmentP    __prism.Prism[*url.URL, string]
	RawFragmentP __prism.Prism[*url.URL, string]
}

// URLPrisms provides prisms for accessing fields of url.URL
type URLPrisms struct {
	Scheme      __prism.Prism[url.URL, string]
	Opaque      __prism.Prism[url.URL, string]
	User        __prism.Prism[url.URL, *url.Userinfo]
	Host        __prism.Prism[url.URL, string]
	Path        __prism.Prism[url.URL, string]
	RawPath     __prism.Prism[url.URL, string]
	OmitHost    __prism.Prism[url.URL, bool]
	ForceQuery  __prism.Prism[url.URL, bool]
	RawQuery    __prism.Prism[url.URL, string]
	Fragment    __prism.Prism[url.URL, string]
	RawFragment __prism.Prism[url.URL, string]
}

// MakeURLLenses creates a new URLLenses with lenses for all fields
func MakeURLLenses() URLLenses {
	// mandatory lenses
	lensScheme := __lens.MakeLensWithName(
		func(s url.URL) string { return s.Scheme },
		func(s url.URL, v string) url.URL { s.Scheme = v; return s },
		"URL.Scheme",
	)
	lensOpaque := __lens.MakeLensWithName(
		func(s url.URL) string { return s.Opaque },
		func(s url.URL, v string) url.URL { s.Opaque = v; return s },
		"URL.Opaque",
	)
	lensUser := __lens.MakeLensWithName(
		func(s url.URL) *url.Userinfo { return s.User },
		func(s url.URL, v *url.Userinfo) url.URL { s.User = v; return s },
		"URL.User",
	)
	lensHost := __lens.MakeLensWithName(
		func(s url.URL) string { return s.Host },
		func(s url.URL, v string) url.URL { s.Host = v; return s },
		"URL.Host",
	)
	lensPath := __lens.MakeLensWithName(
		func(s url.URL) string { return s.Path },
		func(s url.URL, v string) url.URL { s.Path = v; return s },
		"URL.Path",
	)
	lensRawPath := __lens.MakeLensWithName(
		func(s url.URL) string { return s.RawPath },
		func(s url.URL, v string) url.URL { s.RawPath = v; return s },
		"URL.RawPath",
	)
	lensOmitHost := __lens.MakeLensWithName(
		func(s url.URL) bool { return s.OmitHost },
		func(s url.URL, v bool) url.URL { s.OmitHost = v; return s },
		"URL.OmitHost",
	)
	lensForceQuery := __lens.MakeLensWithName(
		func(s url.URL) bool { return s.ForceQuery },
		func(s url.URL, v bool) url.URL { s.ForceQuery = v; return s },
		"URL.ForceQuery",
	)
	lensRawQuery := __lens.MakeLensWithName(
		func(s url.URL) string { return s.RawQuery },
		func(s url.URL, v string) url.URL { s.RawQuery = v; return s },
		"URL.RawQuery",
	)
	lensFragment := __lens.MakeLensWithName(
		func(s url.URL) string { return s.Fragment },
		func(s url.URL, v string) url.URL { s.Fragment = v; return s },
		"URL.Fragment",
	)
	lensRawFragment := __lens.MakeLensWithName(
		func(s url.URL) string { return s.RawFragment },
		func(s url.URL, v string) url.URL { s.RawFragment = v; return s },
		"URL.RawFragment",
	)
	// optional lenses
	lensSchemeO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensScheme)
	lensOpaqueO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensOpaque)
	lensUserO := __lens_option.FromIso[url.URL](__iso_option.FromZero[*url.Userinfo]())(lensUser)
	lensHostO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensHost)
	lensPathO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensPath)
	lensRawPathO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensRawPath)
	lensOmitHostO := __lens_option.FromIso[url.URL](__iso_option.FromZero[bool]())(lensOmitHost)
	lensForceQueryO := __lens_option.FromIso[url.URL](__iso_option.FromZero[bool]())(lensForceQuery)
	lensRawQueryO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensRawQuery)
	lensFragmentO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensFragment)
	lensRawFragmentO := __lens_option.FromIso[url.URL](__iso_option.FromZero[string]())(lensRawFragment)
	return URLLenses{
		// mandatory lenses
		Scheme:      lensScheme,
		Opaque:      lensOpaque,
		User:        lensUser,
		Host:        lensHost,
		Path:        lensPath,
		RawPath:     lensRawPath,
		OmitHost:    lensOmitHost,
		ForceQuery:  lensForceQuery,
		RawQuery:    lensRawQuery,
		Fragment:    lensFragment,
		RawFragment: lensRawFragment,
		// optional lenses
		SchemeO:      lensSchemeO,
		OpaqueO:      lensOpaqueO,
		UserO:        lensUserO,
		HostO:        lensHostO,
		PathO:        lensPathO,
		RawPathO:     lensRawPathO,
		OmitHostO:    lensOmitHostO,
		ForceQueryO:  lensForceQueryO,
		RawQueryO:    lensRawQueryO,
		FragmentO:    lensFragmentO,
		RawFragmentO: lensRawFragmentO,
	}
}

// MakeURLRefLenses creates a new URLRefLenses with lenses for all fields
func MakeURLRefLenses() URLRefLenses {
	// mandatory lenses
	lensScheme := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.Scheme },
		func(s *url.URL, v string) *url.URL { s.Scheme = v; return s },
		"(*url.URL).Scheme",
	)
	lensOpaque := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.Opaque },
		func(s *url.URL, v string) *url.URL { s.Opaque = v; return s },
		"(*url.URL).Opaque",
	)
	lensUser := __lens.MakeLensStrictWithName(
		func(s *url.URL) *url.Userinfo { return s.User },
		func(s *url.URL, v *url.Userinfo) *url.URL { s.User = v; return s },
		"(*url.URL).User",
	)
	lensHost := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.Host },
		func(s *url.URL, v string) *url.URL { s.Host = v; return s },
		"(*url.URL).Host",
	)
	lensPath := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.Path },
		func(s *url.URL, v string) *url.URL { s.Path = v; return s },
		"(*url.URL).Path",
	)
	lensRawPath := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.RawPath },
		func(s *url.URL, v string) *url.URL { s.RawPath = v; return s },
		"(*url.URL).RawPath",
	)
	lensOmitHost := __lens.MakeLensStrictWithName(
		func(s *url.URL) bool { return s.OmitHost },
		func(s *url.URL, v bool) *url.URL { s.OmitHost = v; return s },
		"(*url.URL).OmitHost",
	)
	lensForceQuery := __lens.MakeLensStrictWithName(
		func(s *url.URL) bool { return s.ForceQuery },
		func(s *url.URL, v bool) *url.URL { s.ForceQuery = v; return s },
		"(*url.URL).ForceQuery",
	)
	lensRawQuery := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.RawQuery },
		func(s *url.URL, v string) *url.URL { s.RawQuery = v; return s },
		"(*url.URL).RawQuery",
	)
	lensFragment := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.Fragment },
		func(s *url.URL, v string) *url.URL { s.Fragment = v; return s },
		"(*url.URL).Fragment",
	)
	lensRawFragment := __lens.MakeLensStrictWithName(
		func(s *url.URL) string { return s.RawFragment },
		func(s *url.URL, v string) *url.URL { s.RawFragment = v; return s },
		"(*url.URL).RawFragment",
	)
	// optional lenses
	lensSchemeO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensScheme)
	lensOpaqueO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensOpaque)
	lensUserO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[*url.Userinfo]())(lensUser)
	lensHostO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensHost)
	lensPathO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensPath)
	lensRawPathO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensRawPath)
	lensOmitHostO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[bool]())(lensOmitHost)
	lensForceQueryO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[bool]())(lensForceQuery)
	lensRawQueryO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensRawQuery)
	lensFragmentO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensFragment)
	lensRawFragmentO := __lens_option.FromIso[*url.URL](__iso_option.FromZero[string]())(lensRawFragment)
	return URLRefLenses{
		// mandatory lenses
		Scheme:      lensScheme,
		Opaque:      lensOpaque,
		User:        lensUser,
		Host:        lensHost,
		Path:        lensPath,
		RawPath:     lensRawPath,
		OmitHost:    lensOmitHost,
		ForceQuery:  lensForceQuery,
		RawQuery:    lensRawQuery,
		Fragment:    lensFragment,
		RawFragment: lensRawFragment,
		// optional lenses
		SchemeO:      lensSchemeO,
		OpaqueO:      lensOpaqueO,
		UserO:        lensUserO,
		HostO:        lensHostO,
		PathO:        lensPathO,
		RawPathO:     lensRawPathO,
		OmitHostO:    lensOmitHostO,
		ForceQueryO:  lensForceQueryO,
		RawQueryO:    lensRawQueryO,
		FragmentO:    lensFragmentO,
		RawFragmentO: lensRawFragmentO,
	}
}

// MakeURLPrisms creates a new URLPrisms with prisms for all fields
func MakeURLPrisms() URLPrisms {
	_fromNonZeroScheme := __option.FromNonZero[string]()
	_prismScheme := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroScheme(s.Scheme) },
		func(v string) url.URL {
			return url.URL{Scheme: v}
		},
		"URL.Scheme",
	)
	_fromNonZeroOpaque := __option.FromNonZero[string]()
	_prismOpaque := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroOpaque(s.Opaque) },
		func(v string) url.URL {
			return url.URL{Opaque: v}
		},
		"URL.Opaque",
	)
	_fromNonZeroUser := __option.FromNonZero[*url.Userinfo]()
	_prismUser := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[*url.Userinfo] { return _fromNonZeroUser(s.User) },
		func(v *url.Userinfo) url.URL {
			return url.URL{User: v}
		},
		"URL.User",
	)
	_fromNonZeroHost := __option.FromNonZero[string]()
	_prismHost := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroHost(s.Host) },
		func(v string) url.URL {
			return url.URL{Host: v}
		},
		"URL.Host",
	)
	_fromNonZeroPath := __option.FromNonZero[string]()
	_prismPath := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroPath(s.Path) },
		func(v string) url.URL {
			return url.URL{Path: v}
		},
		"URL.Path",
	)
	_fromNonZeroRawPath := __option.FromNonZero[string]()
	_prismRawPath := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroRawPath(s.RawPath) },
		func(v string) url.URL {
			return url.URL{RawPath: v}
		},
		"URL.RawPath",
	)
	_fromNonZeroOmitHost := __option.FromNonZero[bool]()
	_prismOmitHost := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[bool] { return _fromNonZeroOmitHost(s.OmitHost) },
		func(v bool) url.URL {
			return url.URL{OmitHost: v}
		},
		"URL.OmitHost",
	)
	_fromNonZeroForceQuery := __option.FromNonZero[bool]()
	_prismForceQuery := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[bool] { return _fromNonZeroForceQuery(s.ForceQuery) },
		func(v bool) url.URL {
			return url.URL{ForceQuery: v}
		},
		"URL.ForceQuery",
	)
	_fromNonZeroRawQuery := __option.FromNonZero[string]()
	_prismRawQuery := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroRawQuery(s.RawQuery) },
		func(v string) url.URL {
			return url.URL{RawQuery: v}
		},
		"URL.RawQuery",
	)
	_fromNonZeroFragment := __option.FromNonZero[string]()
	_prismFragment := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroFragment(s.Fragment) },
		func(v string) url.URL {
			return url.URL{Fragment: v}
		},
		"URL.Fragment",
	)
	_fromNonZeroRawFragment := __option.FromNonZero[string]()
	_prismRawFragment := __prism.MakePrismWithName(
		func(s url.URL) __option.Option[string] { return _fromNonZeroRawFragment(s.RawFragment) },
		func(v string) url.URL {
			return url.URL{RawFragment: v}
		},
		"URL.RawFragment",
	)
	return URLPrisms{
		Scheme:      _prismScheme,
		Opaque:      _prismOpaque,
		User:        _prismUser,
		Host:        _prismHost,
		Path:        _prismPath,
		RawPath:     _prismRawPath,
		OmitHost:    _prismOmitHost,
		ForceQuery:  _prismForceQuery,
		RawQuery:    _prismRawQuery,
		Fragment:    _prismFragment,
		RawFragment: _prismRawFragment,
	}
}

// UserinfoRefLenses provides lenses for accessing fields of url.Userinfo via a reference to url.Userinfo
type UserinfoRefLenses struct {
	// mandatory fields
	Username __lens.Lens[*url.Userinfo, string]
	Password __lens.Lens[*url.Userinfo, string]
	// optional fields
	UsernameO __lens_option.LensO[*url.Userinfo, string]
	PasswordO __lens_option.LensO[*url.Userinfo, string]
	// prisms
	UsernameP __prism.Prism[*url.Userinfo, string]
	PasswordP __prism.Prism[*url.Userinfo, string]
}

// MakeUserinfoRefLenses creates a new UserinfoRefLenses with lenses for all fields
func MakeUserinfoRefLenses() UserinfoRefLenses {
	// mandatory lenses
	lensUsername := __lens.MakeLensStrictWithName(
		(*url.Userinfo).Username,
		func(s *url.Userinfo, v string) *url.Userinfo {
			pwd, ok := s.Password()
			if ok {
				return url.UserPassword(v, pwd)
			}
			return url.User(v)
		},
		"(*url.Userinfo).Username",
	)
	lensPassword := __lens.MakeLensStrictWithName(
		func(s *url.Userinfo) string {
			pwd, ok := s.Password()
			if ok {
				return pwd
			}
			return ""
		},
		func(s *url.Userinfo, v string) *url.Userinfo { return url.UserPassword(s.Username(), v) },
		"(*url.Userinfo).Password",
	)
	// optional lenses
	lensUsernameO := __lens_option.FromIso[*url.Userinfo](__iso_option.FromZero[string]())(lensUsername)
	lensPasswordO := __lens.MakeLensStrictWithName(
		__option.Optionize1((*url.Userinfo).Password),
		func(s *url.Userinfo, v __option.Option[string]) *url.Userinfo {
			return __option.MonadFold(v, func() *url.Userinfo { return url.User(s.Username()) }, func(pwd string) *url.Userinfo { return url.UserPassword(s.Username(), pwd) })
		},
		"(*url.Userinfo).Password",
	)
	return UserinfoRefLenses{
		// mandatory lenses
		Username: lensUsername,
		Password: lensPassword,
		// optional lenses
		UsernameO: lensUsernameO,
		PasswordO: lensPasswordO,
	}
}
