package readerresult

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-12-16 13:45:59.7460125 +0100 CET m=+0.011815501

import (
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
)

// PostLenses provides lenses for accessing fields of Post
type PostLenses struct {
	// mandatory fields
	ID     __lens.Lens[Post, int]
	UserID __lens.Lens[Post, int]
	Title  __lens.Lens[Post, string]
	// optional fields
	IDO     __lens_option.LensO[Post, int]
	UserIDO __lens_option.LensO[Post, int]
	TitleO  __lens_option.LensO[Post, string]
}

// PostRefLenses provides lenses for accessing fields of Post via a reference to Post
type PostRefLenses struct {
	// mandatory fields
	ID     __lens.Lens[*Post, int]
	UserID __lens.Lens[*Post, int]
	Title  __lens.Lens[*Post, string]
	// optional fields
	IDO     __lens_option.LensO[*Post, int]
	UserIDO __lens_option.LensO[*Post, int]
	TitleO  __lens_option.LensO[*Post, string]
}

// MakePostLenses creates a new PostLenses with lenses for all fields
func MakePostLenses() PostLenses {
	// mandatory lenses
	lensID := __lens.MakeLensWithName(
		func(s Post) int { return s.ID },
		func(s Post, v int) Post { s.ID = v; return s },
		"Post.ID",
	)
	lensUserID := __lens.MakeLensWithName(
		func(s Post) int { return s.UserID },
		func(s Post, v int) Post { s.UserID = v; return s },
		"Post.UserID",
	)
	lensTitle := __lens.MakeLensWithName(
		func(s Post) string { return s.Title },
		func(s Post, v string) Post { s.Title = v; return s },
		"Post.Title",
	)
	// optional lenses
	lensIDO := __lens_option.FromIso[Post](__iso_option.FromZero[int]())(lensID)
	lensUserIDO := __lens_option.FromIso[Post](__iso_option.FromZero[int]())(lensUserID)
	lensTitleO := __lens_option.FromIso[Post](__iso_option.FromZero[string]())(lensTitle)
	return PostLenses{
		// mandatory lenses
		ID:     lensID,
		UserID: lensUserID,
		Title:  lensTitle,
		// optional lenses
		IDO:     lensIDO,
		UserIDO: lensUserIDO,
		TitleO:  lensTitleO,
	}
}

// MakePostRefLenses creates a new PostRefLenses with lenses for all fields
func MakePostRefLenses() PostRefLenses {
	// mandatory lenses
	lensID := __lens.MakeLensStrictWithName(
		func(s *Post) int { return s.ID },
		func(s *Post, v int) *Post { s.ID = v; return s },
		"(*Post).ID",
	)
	lensUserID := __lens.MakeLensStrictWithName(
		func(s *Post) int { return s.UserID },
		func(s *Post, v int) *Post { s.UserID = v; return s },
		"(*Post).UserID",
	)
	lensTitle := __lens.MakeLensStrictWithName(
		func(s *Post) string { return s.Title },
		func(s *Post, v string) *Post { s.Title = v; return s },
		"(*Post).Title",
	)
	// optional lenses
	lensIDO := __lens_option.FromIso[*Post](__iso_option.FromZero[int]())(lensID)
	lensUserIDO := __lens_option.FromIso[*Post](__iso_option.FromZero[int]())(lensUserID)
	lensTitleO := __lens_option.FromIso[*Post](__iso_option.FromZero[string]())(lensTitle)
	return PostRefLenses{
		// mandatory lenses
		ID:     lensID,
		UserID: lensUserID,
		Title:  lensTitle,
		// optional lenses
		IDO:     lensIDO,
		UserIDO: lensUserIDO,
		TitleO:  lensTitleO,
	}
}

// StateLenses provides lenses for accessing fields of State
type StateLenses struct {
	// mandatory fields
	User     __lens.Lens[State, User]
	Posts    __lens.Lens[State, []Post]
	FullName __lens.Lens[State, string]
	Status   __lens.Lens[State, string]
	// optional fields
	UserO     __lens_option.LensO[State, User]
	FullNameO __lens_option.LensO[State, string]
	StatusO   __lens_option.LensO[State, string]
}

// StateRefLenses provides lenses for accessing fields of State via a reference to State
type StateRefLenses struct {
	// mandatory fields
	User     __lens.Lens[*State, User]
	Posts    __lens.Lens[*State, []Post]
	FullName __lens.Lens[*State, string]
	Status   __lens.Lens[*State, string]
	// optional fields
	UserO     __lens_option.LensO[*State, User]
	FullNameO __lens_option.LensO[*State, string]
	StatusO   __lens_option.LensO[*State, string]
}

// MakeStateLenses creates a new StateLenses with lenses for all fields
func MakeStateLenses() StateLenses {
	// mandatory lenses
	lensUser := __lens.MakeLensWithName(
		func(s State) User { return s.User },
		func(s State, v User) State { s.User = v; return s },
		"State.User",
	)
	lensPosts := __lens.MakeLensWithName(
		func(s State) []Post { return s.Posts },
		func(s State, v []Post) State { s.Posts = v; return s },
		"State.Posts",
	)
	lensFullName := __lens.MakeLensWithName(
		func(s State) string { return s.FullName },
		func(s State, v string) State { s.FullName = v; return s },
		"State.FullName",
	)
	lensStatus := __lens.MakeLensWithName(
		func(s State) string { return s.Status },
		func(s State, v string) State { s.Status = v; return s },
		"State.Status",
	)
	// optional lenses
	lensUserO := __lens_option.FromIso[State](__iso_option.FromZero[User]())(lensUser)
	lensFullNameO := __lens_option.FromIso[State](__iso_option.FromZero[string]())(lensFullName)
	lensStatusO := __lens_option.FromIso[State](__iso_option.FromZero[string]())(lensStatus)
	return StateLenses{
		// mandatory lenses
		User:     lensUser,
		Posts:    lensPosts,
		FullName: lensFullName,
		Status:   lensStatus,
		// optional lenses
		UserO:     lensUserO,
		FullNameO: lensFullNameO,
		StatusO:   lensStatusO,
	}
}

// MakeStateRefLenses creates a new StateRefLenses with lenses for all fields
func MakeStateRefLenses() StateRefLenses {
	// mandatory lenses
	lensUser := __lens.MakeLensStrictWithName(
		func(s *State) User { return s.User },
		func(s *State, v User) *State { s.User = v; return s },
		"(*State).User",
	)
	lensPosts := __lens.MakeLensRefWithName(
		func(s *State) []Post { return s.Posts },
		func(s *State, v []Post) *State { s.Posts = v; return s },
		"(*State).Posts",
	)
	lensFullName := __lens.MakeLensStrictWithName(
		func(s *State) string { return s.FullName },
		func(s *State, v string) *State { s.FullName = v; return s },
		"(*State).FullName",
	)
	lensStatus := __lens.MakeLensStrictWithName(
		func(s *State) string { return s.Status },
		func(s *State, v string) *State { s.Status = v; return s },
		"(*State).Status",
	)
	// optional lenses
	lensUserO := __lens_option.FromIso[*State](__iso_option.FromZero[User]())(lensUser)
	lensFullNameO := __lens_option.FromIso[*State](__iso_option.FromZero[string]())(lensFullName)
	lensStatusO := __lens_option.FromIso[*State](__iso_option.FromZero[string]())(lensStatus)
	return StateRefLenses{
		// mandatory lenses
		User:     lensUser,
		Posts:    lensPosts,
		FullName: lensFullName,
		Status:   lensStatus,
		// optional lenses
		UserO:     lensUserO,
		FullNameO: lensFullNameO,
		StatusO:   lensStatusO,
	}
}

// SimpleStateLenses provides lenses for accessing fields of SimpleState
type SimpleStateLenses struct {
	// mandatory fields
	Value __lens.Lens[SimpleState, int]
	// optional fields
	ValueO __lens_option.LensO[SimpleState, int]
}

// SimpleStateRefLenses provides lenses for accessing fields of SimpleState via a reference to SimpleState
type SimpleStateRefLenses struct {
	// mandatory fields
	Value __lens.Lens[*SimpleState, int]
	// optional fields
	ValueO __lens_option.LensO[*SimpleState, int]
}

// MakeSimpleStateLenses creates a new SimpleStateLenses with lenses for all fields
func MakeSimpleStateLenses() SimpleStateLenses {
	// mandatory lenses
	lensValue := __lens.MakeLensWithName(
		func(s SimpleState) int { return s.Value },
		func(s SimpleState, v int) SimpleState { s.Value = v; return s },
		"SimpleState.Value",
	)
	// optional lenses
	lensValueO := __lens_option.FromIso[SimpleState](__iso_option.FromZero[int]())(lensValue)
	return SimpleStateLenses{
		// mandatory lenses
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// MakeSimpleStateRefLenses creates a new SimpleStateRefLenses with lenses for all fields
func MakeSimpleStateRefLenses() SimpleStateRefLenses {
	// mandatory lenses
	lensValue := __lens.MakeLensStrictWithName(
		func(s *SimpleState) int { return s.Value },
		func(s *SimpleState, v int) *SimpleState { s.Value = v; return s },
		"(*SimpleState).Value",
	)
	// optional lenses
	lensValueO := __lens_option.FromIso[*SimpleState](__iso_option.FromZero[int]())(lensValue)
	return SimpleStateRefLenses{
		// mandatory lenses
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// NameStateLenses provides lenses for accessing fields of NameState
type NameStateLenses struct {
	// mandatory fields
	FirstName __lens.Lens[NameState, string]
	LastName  __lens.Lens[NameState, string]
	FullName  __lens.Lens[NameState, string]
	// optional fields
	FirstNameO __lens_option.LensO[NameState, string]
	LastNameO  __lens_option.LensO[NameState, string]
	FullNameO  __lens_option.LensO[NameState, string]
}

// NameStateRefLenses provides lenses for accessing fields of NameState via a reference to NameState
type NameStateRefLenses struct {
	// mandatory fields
	FirstName __lens.Lens[*NameState, string]
	LastName  __lens.Lens[*NameState, string]
	FullName  __lens.Lens[*NameState, string]
	// optional fields
	FirstNameO __lens_option.LensO[*NameState, string]
	LastNameO  __lens_option.LensO[*NameState, string]
	FullNameO  __lens_option.LensO[*NameState, string]
}

// MakeNameStateLenses creates a new NameStateLenses with lenses for all fields
func MakeNameStateLenses() NameStateLenses {
	// mandatory lenses
	lensFirstName := __lens.MakeLensWithName(
		func(s NameState) string { return s.FirstName },
		func(s NameState, v string) NameState { s.FirstName = v; return s },
		"NameState.FirstName",
	)
	lensLastName := __lens.MakeLensWithName(
		func(s NameState) string { return s.LastName },
		func(s NameState, v string) NameState { s.LastName = v; return s },
		"NameState.LastName",
	)
	lensFullName := __lens.MakeLensWithName(
		func(s NameState) string { return s.FullName },
		func(s NameState, v string) NameState { s.FullName = v; return s },
		"NameState.FullName",
	)
	// optional lenses
	lensFirstNameO := __lens_option.FromIso[NameState](__iso_option.FromZero[string]())(lensFirstName)
	lensLastNameO := __lens_option.FromIso[NameState](__iso_option.FromZero[string]())(lensLastName)
	lensFullNameO := __lens_option.FromIso[NameState](__iso_option.FromZero[string]())(lensFullName)
	return NameStateLenses{
		// mandatory lenses
		FirstName: lensFirstName,
		LastName:  lensLastName,
		FullName:  lensFullName,
		// optional lenses
		FirstNameO: lensFirstNameO,
		LastNameO:  lensLastNameO,
		FullNameO:  lensFullNameO,
	}
}

// MakeNameStateRefLenses creates a new NameStateRefLenses with lenses for all fields
func MakeNameStateRefLenses() NameStateRefLenses {
	// mandatory lenses
	lensFirstName := __lens.MakeLensStrictWithName(
		func(s *NameState) string { return s.FirstName },
		func(s *NameState, v string) *NameState { s.FirstName = v; return s },
		"(*NameState).FirstName",
	)
	lensLastName := __lens.MakeLensStrictWithName(
		func(s *NameState) string { return s.LastName },
		func(s *NameState, v string) *NameState { s.LastName = v; return s },
		"(*NameState).LastName",
	)
	lensFullName := __lens.MakeLensStrictWithName(
		func(s *NameState) string { return s.FullName },
		func(s *NameState, v string) *NameState { s.FullName = v; return s },
		"(*NameState).FullName",
	)
	// optional lenses
	lensFirstNameO := __lens_option.FromIso[*NameState](__iso_option.FromZero[string]())(lensFirstName)
	lensLastNameO := __lens_option.FromIso[*NameState](__iso_option.FromZero[string]())(lensLastName)
	lensFullNameO := __lens_option.FromIso[*NameState](__iso_option.FromZero[string]())(lensFullName)
	return NameStateRefLenses{
		// mandatory lenses
		FirstName: lensFirstName,
		LastName:  lensLastName,
		FullName:  lensFullName,
		// optional lenses
		FirstNameO: lensFirstNameO,
		LastNameO:  lensLastNameO,
		FullNameO:  lensFullNameO,
	}
}

// StatusStateLenses provides lenses for accessing fields of StatusState
type StatusStateLenses struct {
	// mandatory fields
	Status __lens.Lens[StatusState, string]
	// optional fields
	StatusO __lens_option.LensO[StatusState, string]
}

// StatusStateRefLenses provides lenses for accessing fields of StatusState via a reference to StatusState
type StatusStateRefLenses struct {
	// mandatory fields
	Status __lens.Lens[*StatusState, string]
	// optional fields
	StatusO __lens_option.LensO[*StatusState, string]
}

// MakeStatusStateLenses creates a new StatusStateLenses with lenses for all fields
func MakeStatusStateLenses() StatusStateLenses {
	// mandatory lenses
	lensStatus := __lens.MakeLensWithName(
		func(s StatusState) string { return s.Status },
		func(s StatusState, v string) StatusState { s.Status = v; return s },
		"StatusState.Status",
	)
	// optional lenses
	lensStatusO := __lens_option.FromIso[StatusState](__iso_option.FromZero[string]())(lensStatus)
	return StatusStateLenses{
		// mandatory lenses
		Status: lensStatus,
		// optional lenses
		StatusO: lensStatusO,
	}
}

// MakeStatusStateRefLenses creates a new StatusStateRefLenses with lenses for all fields
func MakeStatusStateRefLenses() StatusStateRefLenses {
	// mandatory lenses
	lensStatus := __lens.MakeLensStrictWithName(
		func(s *StatusState) string { return s.Status },
		func(s *StatusState, v string) *StatusState { s.Status = v; return s },
		"(*StatusState).Status",
	)
	// optional lenses
	lensStatusO := __lens_option.FromIso[*StatusState](__iso_option.FromZero[string]())(lensStatus)
	return StatusStateRefLenses{
		// mandatory lenses
		Status: lensStatus,
		// optional lenses
		StatusO: lensStatusO,
	}
}

// UserStateLenses provides lenses for accessing fields of UserState
type UserStateLenses struct {
	// mandatory fields
	User __lens.Lens[UserState, User]
	// optional fields
	UserO __lens_option.LensO[UserState, User]
}

// UserStateRefLenses provides lenses for accessing fields of UserState via a reference to UserState
type UserStateRefLenses struct {
	// mandatory fields
	User __lens.Lens[*UserState, User]
	// optional fields
	UserO __lens_option.LensO[*UserState, User]
}

// MakeUserStateLenses creates a new UserStateLenses with lenses for all fields
func MakeUserStateLenses() UserStateLenses {
	// mandatory lenses
	lensUser := __lens.MakeLensWithName(
		func(s UserState) User { return s.User },
		func(s UserState, v User) UserState { s.User = v; return s },
		"UserState.User",
	)
	// optional lenses
	lensUserO := __lens_option.FromIso[UserState](__iso_option.FromZero[User]())(lensUser)
	return UserStateLenses{
		// mandatory lenses
		User: lensUser,
		// optional lenses
		UserO: lensUserO,
	}
}

// MakeUserStateRefLenses creates a new UserStateRefLenses with lenses for all fields
func MakeUserStateRefLenses() UserStateRefLenses {
	// mandatory lenses
	lensUser := __lens.MakeLensStrictWithName(
		func(s *UserState) User { return s.User },
		func(s *UserState, v User) *UserState { s.User = v; return s },
		"(*UserState).User",
	)
	// optional lenses
	lensUserO := __lens_option.FromIso[*UserState](__iso_option.FromZero[User]())(lensUser)
	return UserStateRefLenses{
		// mandatory lenses
		User: lensUser,
		// optional lenses
		UserO: lensUserO,
	}
}

// ConfigStateLenses provides lenses for accessing fields of ConfigState
type ConfigStateLenses struct {
	// mandatory fields
	Config __lens.Lens[ConfigState, string]
	// optional fields
	ConfigO __lens_option.LensO[ConfigState, string]
}

// ConfigStateRefLenses provides lenses for accessing fields of ConfigState via a reference to ConfigState
type ConfigStateRefLenses struct {
	// mandatory fields
	Config __lens.Lens[*ConfigState, string]
	// optional fields
	ConfigO __lens_option.LensO[*ConfigState, string]
}

// MakeConfigStateLenses creates a new ConfigStateLenses with lenses for all fields
func MakeConfigStateLenses() ConfigStateLenses {
	// mandatory lenses
	lensConfig := __lens.MakeLensWithName(
		func(s ConfigState) string { return s.Config },
		func(s ConfigState, v string) ConfigState { s.Config = v; return s },
		"ConfigState.Config",
	)
	// optional lenses
	lensConfigO := __lens_option.FromIso[ConfigState](__iso_option.FromZero[string]())(lensConfig)
	return ConfigStateLenses{
		// mandatory lenses
		Config: lensConfig,
		// optional lenses
		ConfigO: lensConfigO,
	}
}

// MakeConfigStateRefLenses creates a new ConfigStateRefLenses with lenses for all fields
func MakeConfigStateRefLenses() ConfigStateRefLenses {
	// mandatory lenses
	lensConfig := __lens.MakeLensStrictWithName(
		func(s *ConfigState) string { return s.Config },
		func(s *ConfigState, v string) *ConfigState { s.Config = v; return s },
		"(*ConfigState).Config",
	)
	// optional lenses
	lensConfigO := __lens_option.FromIso[*ConfigState](__iso_option.FromZero[string]())(lensConfig)
	return ConfigStateRefLenses{
		// mandatory lenses
		Config: lensConfig,
		// optional lenses
		ConfigO: lensConfigO,
	}
}

// NumberStateLenses provides lenses for accessing fields of NumberState
type NumberStateLenses struct {
	// mandatory fields
	Number __lens.Lens[NumberState, int]
	// optional fields
	NumberO __lens_option.LensO[NumberState, int]
}

// NumberStateRefLenses provides lenses for accessing fields of NumberState via a reference to NumberState
type NumberStateRefLenses struct {
	// mandatory fields
	Number __lens.Lens[*NumberState, int]
	// optional fields
	NumberO __lens_option.LensO[*NumberState, int]
}

// MakeNumberStateLenses creates a new NumberStateLenses with lenses for all fields
func MakeNumberStateLenses() NumberStateLenses {
	// mandatory lenses
	lensNumber := __lens.MakeLensWithName(
		func(s NumberState) int { return s.Number },
		func(s NumberState, v int) NumberState { s.Number = v; return s },
		"NumberState.Number",
	)
	// optional lenses
	lensNumberO := __lens_option.FromIso[NumberState](__iso_option.FromZero[int]())(lensNumber)
	return NumberStateLenses{
		// mandatory lenses
		Number: lensNumber,
		// optional lenses
		NumberO: lensNumberO,
	}
}

// MakeNumberStateRefLenses creates a new NumberStateRefLenses with lenses for all fields
func MakeNumberStateRefLenses() NumberStateRefLenses {
	// mandatory lenses
	lensNumber := __lens.MakeLensStrictWithName(
		func(s *NumberState) int { return s.Number },
		func(s *NumberState, v int) *NumberState { s.Number = v; return s },
		"(*NumberState).Number",
	)
	// optional lenses
	lensNumberO := __lens_option.FromIso[*NumberState](__iso_option.FromZero[int]())(lensNumber)
	return NumberStateRefLenses{
		// mandatory lenses
		Number: lensNumber,
		// optional lenses
		NumberO: lensNumberO,
	}
}

// DataStateLenses provides lenses for accessing fields of DataState
type DataStateLenses struct {
	// mandatory fields
	Data __lens.Lens[DataState, string]
	// optional fields
	DataO __lens_option.LensO[DataState, string]
}

// DataStateRefLenses provides lenses for accessing fields of DataState via a reference to DataState
type DataStateRefLenses struct {
	// mandatory fields
	Data __lens.Lens[*DataState, string]
	// optional fields
	DataO __lens_option.LensO[*DataState, string]
}

// MakeDataStateLenses creates a new DataStateLenses with lenses for all fields
func MakeDataStateLenses() DataStateLenses {
	// mandatory lenses
	lensData := __lens.MakeLensWithName(
		func(s DataState) string { return s.Data },
		func(s DataState, v string) DataState { s.Data = v; return s },
		"DataState.Data",
	)
	// optional lenses
	lensDataO := __lens_option.FromIso[DataState](__iso_option.FromZero[string]())(lensData)
	return DataStateLenses{
		// mandatory lenses
		Data: lensData,
		// optional lenses
		DataO: lensDataO,
	}
}

// MakeDataStateRefLenses creates a new DataStateRefLenses with lenses for all fields
func MakeDataStateRefLenses() DataStateRefLenses {
	// mandatory lenses
	lensData := __lens.MakeLensStrictWithName(
		func(s *DataState) string { return s.Data },
		func(s *DataState, v string) *DataState { s.Data = v; return s },
		"(*DataState).Data",
	)
	// optional lenses
	lensDataO := __lens_option.FromIso[*DataState](__iso_option.FromZero[string]())(lensData)
	return DataStateRefLenses{
		// mandatory lenses
		Data: lensData,
		// optional lenses
		DataO: lensDataO,
	}
}

// RequestStateLenses provides lenses for accessing fields of RequestState
type RequestStateLenses struct {
	// mandatory fields
	RequestID __lens.Lens[RequestState, string]
	// optional fields
	RequestIDO __lens_option.LensO[RequestState, string]
}

// RequestStateRefLenses provides lenses for accessing fields of RequestState via a reference to RequestState
type RequestStateRefLenses struct {
	// mandatory fields
	RequestID __lens.Lens[*RequestState, string]
	// optional fields
	RequestIDO __lens_option.LensO[*RequestState, string]
}

// MakeRequestStateLenses creates a new RequestStateLenses with lenses for all fields
func MakeRequestStateLenses() RequestStateLenses {
	// mandatory lenses
	lensRequestID := __lens.MakeLensWithName(
		func(s RequestState) string { return s.RequestID },
		func(s RequestState, v string) RequestState { s.RequestID = v; return s },
		"RequestState.RequestID",
	)
	// optional lenses
	lensRequestIDO := __lens_option.FromIso[RequestState](__iso_option.FromZero[string]())(lensRequestID)
	return RequestStateLenses{
		// mandatory lenses
		RequestID: lensRequestID,
		// optional lenses
		RequestIDO: lensRequestIDO,
	}
}

// MakeRequestStateRefLenses creates a new RequestStateRefLenses with lenses for all fields
func MakeRequestStateRefLenses() RequestStateRefLenses {
	// mandatory lenses
	lensRequestID := __lens.MakeLensStrictWithName(
		func(s *RequestState) string { return s.RequestID },
		func(s *RequestState, v string) *RequestState { s.RequestID = v; return s },
		"(*RequestState).RequestID",
	)
	// optional lenses
	lensRequestIDO := __lens_option.FromIso[*RequestState](__iso_option.FromZero[string]())(lensRequestID)
	return RequestStateRefLenses{
		// mandatory lenses
		RequestID: lensRequestID,
		// optional lenses
		RequestIDO: lensRequestIDO,
	}
}

// ValueStateLenses provides lenses for accessing fields of ValueState
type ValueStateLenses struct {
	// mandatory fields
	Value __lens.Lens[ValueState, int]
	// optional fields
	ValueO __lens_option.LensO[ValueState, int]
}

// ValueStateRefLenses provides lenses for accessing fields of ValueState via a reference to ValueState
type ValueStateRefLenses struct {
	// mandatory fields
	Value __lens.Lens[*ValueState, int]
	// optional fields
	ValueO __lens_option.LensO[*ValueState, int]
}

// MakeValueStateLenses creates a new ValueStateLenses with lenses for all fields
func MakeValueStateLenses() ValueStateLenses {
	// mandatory lenses
	lensValue := __lens.MakeLensWithName(
		func(s ValueState) int { return s.Value },
		func(s ValueState, v int) ValueState { s.Value = v; return s },
		"ValueState.Value",
	)
	// optional lenses
	lensValueO := __lens_option.FromIso[ValueState](__iso_option.FromZero[int]())(lensValue)
	return ValueStateLenses{
		// mandatory lenses
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// MakeValueStateRefLenses creates a new ValueStateRefLenses with lenses for all fields
func MakeValueStateRefLenses() ValueStateRefLenses {
	// mandatory lenses
	lensValue := __lens.MakeLensStrictWithName(
		func(s *ValueState) int { return s.Value },
		func(s *ValueState, v int) *ValueState { s.Value = v; return s },
		"(*ValueState).Value",
	)
	// optional lenses
	lensValueO := __lens_option.FromIso[*ValueState](__iso_option.FromZero[int]())(lensValue)
	return ValueStateRefLenses{
		// mandatory lenses
		Value: lensValue,
		// optional lenses
		ValueO: lensValueO,
	}
}

// ResultStateLenses provides lenses for accessing fields of ResultState
type ResultStateLenses struct {
	// mandatory fields
	Result __lens.Lens[ResultState, string]
	// optional fields
	ResultO __lens_option.LensO[ResultState, string]
}

// ResultStateRefLenses provides lenses for accessing fields of ResultState via a reference to ResultState
type ResultStateRefLenses struct {
	// mandatory fields
	Result __lens.Lens[*ResultState, string]
	// optional fields
	ResultO __lens_option.LensO[*ResultState, string]
}

// MakeResultStateLenses creates a new ResultStateLenses with lenses for all fields
func MakeResultStateLenses() ResultStateLenses {
	// mandatory lenses
	lensResult := __lens.MakeLensWithName(
		func(s ResultState) string { return s.Result },
		func(s ResultState, v string) ResultState { s.Result = v; return s },
		"ResultState.Result",
	)
	// optional lenses
	lensResultO := __lens_option.FromIso[ResultState](__iso_option.FromZero[string]())(lensResult)
	return ResultStateLenses{
		// mandatory lenses
		Result: lensResult,
		// optional lenses
		ResultO: lensResultO,
	}
}

// MakeResultStateRefLenses creates a new ResultStateRefLenses with lenses for all fields
func MakeResultStateRefLenses() ResultStateRefLenses {
	// mandatory lenses
	lensResult := __lens.MakeLensStrictWithName(
		func(s *ResultState) string { return s.Result },
		func(s *ResultState, v string) *ResultState { s.Result = v; return s },
		"(*ResultState).Result",
	)
	// optional lenses
	lensResultO := __lens_option.FromIso[*ResultState](__iso_option.FromZero[string]())(lensResult)
	return ResultStateRefLenses{
		// mandatory lenses
		Result: lensResult,
		// optional lenses
		ResultO: lensResultO,
	}
}

// EnvStateLenses provides lenses for accessing fields of EnvState
type EnvStateLenses struct {
	// mandatory fields
	Environment __lens.Lens[EnvState, string]
	// optional fields
	EnvironmentO __lens_option.LensO[EnvState, string]
}

// EnvStateRefLenses provides lenses for accessing fields of EnvState via a reference to EnvState
type EnvStateRefLenses struct {
	// mandatory fields
	Environment __lens.Lens[*EnvState, string]
	// optional fields
	EnvironmentO __lens_option.LensO[*EnvState, string]
}

// MakeEnvStateLenses creates a new EnvStateLenses with lenses for all fields
func MakeEnvStateLenses() EnvStateLenses {
	// mandatory lenses
	lensEnvironment := __lens.MakeLensWithName(
		func(s EnvState) string { return s.Environment },
		func(s EnvState, v string) EnvState { s.Environment = v; return s },
		"EnvState.Environment",
	)
	// optional lenses
	lensEnvironmentO := __lens_option.FromIso[EnvState](__iso_option.FromZero[string]())(lensEnvironment)
	return EnvStateLenses{
		// mandatory lenses
		Environment: lensEnvironment,
		// optional lenses
		EnvironmentO: lensEnvironmentO,
	}
}

// MakeEnvStateRefLenses creates a new EnvStateRefLenses with lenses for all fields
func MakeEnvStateRefLenses() EnvStateRefLenses {
	// mandatory lenses
	lensEnvironment := __lens.MakeLensStrictWithName(
		func(s *EnvState) string { return s.Environment },
		func(s *EnvState, v string) *EnvState { s.Environment = v; return s },
		"(*EnvState).Environment",
	)
	// optional lenses
	lensEnvironmentO := __lens_option.FromIso[*EnvState](__iso_option.FromZero[string]())(lensEnvironment)
	return EnvStateRefLenses{
		// mandatory lenses
		Environment: lensEnvironment,
		// optional lenses
		EnvironmentO: lensEnvironmentO,
	}
}

// ScoreStateLenses provides lenses for accessing fields of ScoreState
type ScoreStateLenses struct {
	// mandatory fields
	Score __lens.Lens[ScoreState, int]
	// optional fields
	ScoreO __lens_option.LensO[ScoreState, int]
}

// ScoreStateRefLenses provides lenses for accessing fields of ScoreState via a reference to ScoreState
type ScoreStateRefLenses struct {
	// mandatory fields
	Score __lens.Lens[*ScoreState, int]
	// optional fields
	ScoreO __lens_option.LensO[*ScoreState, int]
}

// MakeScoreStateLenses creates a new ScoreStateLenses with lenses for all fields
func MakeScoreStateLenses() ScoreStateLenses {
	// mandatory lenses
	lensScore := __lens.MakeLensWithName(
		func(s ScoreState) int { return s.Score },
		func(s ScoreState, v int) ScoreState { s.Score = v; return s },
		"ScoreState.Score",
	)
	// optional lenses
	lensScoreO := __lens_option.FromIso[ScoreState](__iso_option.FromZero[int]())(lensScore)
	return ScoreStateLenses{
		// mandatory lenses
		Score: lensScore,
		// optional lenses
		ScoreO: lensScoreO,
	}
}

// MakeScoreStateRefLenses creates a new ScoreStateRefLenses with lenses for all fields
func MakeScoreStateRefLenses() ScoreStateRefLenses {
	// mandatory lenses
	lensScore := __lens.MakeLensStrictWithName(
		func(s *ScoreState) int { return s.Score },
		func(s *ScoreState, v int) *ScoreState { s.Score = v; return s },
		"(*ScoreState).Score",
	)
	// optional lenses
	lensScoreO := __lens_option.FromIso[*ScoreState](__iso_option.FromZero[int]())(lensScore)
	return ScoreStateRefLenses{
		// mandatory lenses
		Score: lensScore,
		// optional lenses
		ScoreO: lensScoreO,
	}
}

// MessageStateLenses provides lenses for accessing fields of MessageState
type MessageStateLenses struct {
	// mandatory fields
	Message __lens.Lens[MessageState, string]
	// optional fields
	MessageO __lens_option.LensO[MessageState, string]
}

// MessageStateRefLenses provides lenses for accessing fields of MessageState via a reference to MessageState
type MessageStateRefLenses struct {
	// mandatory fields
	Message __lens.Lens[*MessageState, string]
	// optional fields
	MessageO __lens_option.LensO[*MessageState, string]
}

// MakeMessageStateLenses creates a new MessageStateLenses with lenses for all fields
func MakeMessageStateLenses() MessageStateLenses {
	// mandatory lenses
	lensMessage := __lens.MakeLensWithName(
		func(s MessageState) string { return s.Message },
		func(s MessageState, v string) MessageState { s.Message = v; return s },
		"MessageState.Message",
	)
	// optional lenses
	lensMessageO := __lens_option.FromIso[MessageState](__iso_option.FromZero[string]())(lensMessage)
	return MessageStateLenses{
		// mandatory lenses
		Message: lensMessage,
		// optional lenses
		MessageO: lensMessageO,
	}
}

// MakeMessageStateRefLenses creates a new MessageStateRefLenses with lenses for all fields
func MakeMessageStateRefLenses() MessageStateRefLenses {
	// mandatory lenses
	lensMessage := __lens.MakeLensStrictWithName(
		func(s *MessageState) string { return s.Message },
		func(s *MessageState, v string) *MessageState { s.Message = v; return s },
		"(*MessageState).Message",
	)
	// optional lenses
	lensMessageO := __lens_option.FromIso[*MessageState](__iso_option.FromZero[string]())(lensMessage)
	return MessageStateRefLenses{
		// mandatory lenses
		Message: lensMessage,
		// optional lenses
		MessageO: lensMessageO,
	}
}

// UserLenses provides lenses for accessing fields of User
type UserLenses struct {
	// mandatory fields
	ID   __lens.Lens[User, int]
	Name __lens.Lens[User, string]
	// optional fields
	IDO   __lens_option.LensO[User, int]
	NameO __lens_option.LensO[User, string]
}

// UserRefLenses provides lenses for accessing fields of User via a reference to User
type UserRefLenses struct {
	// mandatory fields
	ID   __lens.Lens[*User, int]
	Name __lens.Lens[*User, string]
	// optional fields
	IDO   __lens_option.LensO[*User, int]
	NameO __lens_option.LensO[*User, string]
}

// MakeUserLenses creates a new UserLenses with lenses for all fields
func MakeUserLenses() UserLenses {
	// mandatory lenses
	lensID := __lens.MakeLensWithName(
		func(s User) int { return s.ID },
		func(s User, v int) User { s.ID = v; return s },
		"User.ID",
	)
	lensName := __lens.MakeLensWithName(
		func(s User) string { return s.Name },
		func(s User, v string) User { s.Name = v; return s },
		"User.Name",
	)
	// optional lenses
	lensIDO := __lens_option.FromIso[User](__iso_option.FromZero[int]())(lensID)
	lensNameO := __lens_option.FromIso[User](__iso_option.FromZero[string]())(lensName)
	return UserLenses{
		// mandatory lenses
		ID:   lensID,
		Name: lensName,
		// optional lenses
		IDO:   lensIDO,
		NameO: lensNameO,
	}
}

// MakeUserRefLenses creates a new UserRefLenses with lenses for all fields
func MakeUserRefLenses() UserRefLenses {
	// mandatory lenses
	lensID := __lens.MakeLensStrictWithName(
		func(s *User) int { return s.ID },
		func(s *User, v int) *User { s.ID = v; return s },
		"(*User).ID",
	)
	lensName := __lens.MakeLensStrictWithName(
		func(s *User) string { return s.Name },
		func(s *User, v string) *User { s.Name = v; return s },
		"(*User).Name",
	)
	// optional lenses
	lensIDO := __lens_option.FromIso[*User](__iso_option.FromZero[int]())(lensID)
	lensNameO := __lens_option.FromIso[*User](__iso_option.FromZero[string]())(lensName)
	return UserRefLenses{
		// mandatory lenses
		ID:   lensID,
		Name: lensName,
		// optional lenses
		IDO:   lensIDO,
		NameO: lensNameO,
	}
}

// ConfigLenses provides lenses for accessing fields of Config
type ConfigLenses struct {
	// mandatory fields
	Port        __lens.Lens[Config, int]
	DatabaseURL __lens.Lens[Config, string]
	// optional fields
	PortO        __lens_option.LensO[Config, int]
	DatabaseURLO __lens_option.LensO[Config, string]
}

// ConfigRefLenses provides lenses for accessing fields of Config via a reference to Config
type ConfigRefLenses struct {
	// mandatory fields
	Port        __lens.Lens[*Config, int]
	DatabaseURL __lens.Lens[*Config, string]
	// optional fields
	PortO        __lens_option.LensO[*Config, int]
	DatabaseURLO __lens_option.LensO[*Config, string]
}

// MakeConfigLenses creates a new ConfigLenses with lenses for all fields
func MakeConfigLenses() ConfigLenses {
	// mandatory lenses
	lensPort := __lens.MakeLensWithName(
		func(s Config) int { return s.Port },
		func(s Config, v int) Config { s.Port = v; return s },
		"Config.Port",
	)
	lensDatabaseURL := __lens.MakeLensWithName(
		func(s Config) string { return s.DatabaseURL },
		func(s Config, v string) Config { s.DatabaseURL = v; return s },
		"Config.DatabaseURL",
	)
	// optional lenses
	lensPortO := __lens_option.FromIso[Config](__iso_option.FromZero[int]())(lensPort)
	lensDatabaseURLO := __lens_option.FromIso[Config](__iso_option.FromZero[string]())(lensDatabaseURL)
	return ConfigLenses{
		// mandatory lenses
		Port:        lensPort,
		DatabaseURL: lensDatabaseURL,
		// optional lenses
		PortO:        lensPortO,
		DatabaseURLO: lensDatabaseURLO,
	}
}

// MakeConfigRefLenses creates a new ConfigRefLenses with lenses for all fields
func MakeConfigRefLenses() ConfigRefLenses {
	// mandatory lenses
	lensPort := __lens.MakeLensStrictWithName(
		func(s *Config) int { return s.Port },
		func(s *Config, v int) *Config { s.Port = v; return s },
		"(*Config).Port",
	)
	lensDatabaseURL := __lens.MakeLensStrictWithName(
		func(s *Config) string { return s.DatabaseURL },
		func(s *Config, v string) *Config { s.DatabaseURL = v; return s },
		"(*Config).DatabaseURL",
	)
	// optional lenses
	lensPortO := __lens_option.FromIso[*Config](__iso_option.FromZero[int]())(lensPort)
	lensDatabaseURLO := __lens_option.FromIso[*Config](__iso_option.FromZero[string]())(lensDatabaseURL)
	return ConfigRefLenses{
		// mandatory lenses
		Port:        lensPort,
		DatabaseURL: lensDatabaseURL,
		// optional lenses
		PortO:        lensPortO,
		DatabaseURLO: lensDatabaseURLO,
	}
}
